---
- name: Validate user_ssh_name
  ansible.builtin.assert:
    that:
      - user_ssh_name is defined
      - user_ssh_name is string
    fail_msg: user_ssh_name must be a string

- name: Validate user_ssh_keys
  ansible.builtin.assert:
    that:
      - user_ssh_keys is defined
      - user_ssh_keys is sequence
      - user_ssh_keys is not string
    fail_msg: user_ssh_keys must be a list

- name: Validate each user_ssh_key
  loop: "{{ user_ssh_keys }}"
  ansible.builtin.assert:
    that:
      - item is string
    fail_msg: each user_ssh_key must be a string

- name: Populate service facts
  ansible.builtin.service_facts:

- name: Verify that sshd is available
  ansible.builtin.assert:
    that:
      - "'ssh' in ansible_facts.services"
    fail_msg: sshd must be available

- name: Setup authorized_keys for user
  ansible.posix.authorized_key:
    user: "{{ user_ssh_name }}"
    state: present
    exclusive: true
    key: |
      {% for user_ssh_key in user_ssh_keys %}
      {{ user_ssh_key }}
      {% endfor %}

- name: Prepare sshd_config snippet to allow user
  notify: Reload sshd - role {{ role_name }}
  ansible.builtin.copy:
    content: "AllowUsers {{ user_ssh_name }}"
    dest: "{{ user_ssh_sshd_config_d }}/{{ user_ssh_name }}.conf"
    owner: root
    group: root
    mode: "644"
