---
# Purpose: bring the instance to the desired state by running the role under test.
# Molecule calls this playbook with `molecule converge`.
- name: Converge
  hosts: user_ssh
  gather_facts: true # Disable if your role does not rely on facts
  tasks:
    - name: Apply role under test
      ansible.builtin.import_role:
        # roles can be invoked by name or by path
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
